language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install ."
# command to run tests
script: 
    - cd tests/unit && python -m unittest discover
    - cd tests/integration && python -m unittest discover
    - flake8 tests stackexchange setup.py
